### ISSUE TITLE
Enable event types by sending message templates to Seq

### ISSUE THREAD

**Issue by nblumhardt** [aloneguid/logmagic#8]
Hi!

I just checked out the Seq sink and found it's sending the [formatted message](https://github.com/aloneguid/logmagic/blob/master/src/LogMagic/Writers/SeqWriter.cs#L80) rather than the original template to Seq, which means it misses out on [event type support](https://nblumhardt.com/2016/07/event-types-structured-logging-concepts-in-net-4/).

It doesn't look like it would be too hard to modify - should I have a shot at getting a PR together?

**Comment by aloneguid** [comment]
@nblumhardt you are most welcome )
